language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y dpkg-dev fakeroot lintian
install:
  - pip install coveralls
  - python setup.py install
script:
  sudo "$VIRTUAL_ENV/bin/coverage" run --source=deb_pkg_tools setup.py test
after_success:
  coveralls
