language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y binutils dpkg-dev fakeroot lintian
install: python setup.py install
script: python setup.py test
