language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# Install the dependencies of deb-pkg-tools before running the test suite.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y dpkg-dev fakeroot lintian python-apt
# Prepare to submit coverage statistics to coveralls.io.
install:
  - pip install coveralls
  - python setup.py install
# Run the test suite as root so that all tests run (even the `dangerous ones').
script:
  sudo "$VIRTUAL_ENV/bin/coverage" run --source=deb_pkg_tools setup.py test
# Submit coverage statistics to coveralls.io after successful runs.
after_success:
  coveralls
