sudo: required
language: python
dist: xenial
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
      dist: bionic
    - python: 3.7
      dist: bionic
    - python: pypy
virtualenv:
  system_site_packages: true
install:
  - scripts/install-on-travis.sh
script:
  - make check
  - make full-coverage
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
